# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.3"

gem "dependency-a"
gem "dependency-b", "0.0.0"

group :test do
  gem "dependency-c"
end

group :development do
  gem "dependency-d"
end
